"use strict";

function metric(label, value, detail="") {
  return `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-detail">${detail}</div></div>`;
}
function quoteDetails(q) {
  return q ? `${escapeHTML(q.status)} · ${escapeHTML(q.source)}<br>Observed: ${escapeHTML(q.observed_at)}<br>Fetched: ${escapeHTML(q.fetched_at || "frozen replay")}` : "Unavailable · awaiting provider data";
}
function forecastCard(f, horizon) {
  if (!f) return `<div class="forecast"><h4>${horizon === 5 ? "Five-session direction" : "Next-session close"}</h4><p>No eligible model forecast yet.</p></div>`;
  return `<div class="forecast"><h4>${horizon === 5 ? "Five-session direction" : "Next-session close"}</h4><strong>${horizon === 5 ? `${escapeHTML(f.direction)} · ${percent(f.confidence)} probability` : money(f.estimate)}</strong><p>Reference ${dateLabel(f.date)} · ${money(f.price)}<br>Target ${dateLabel(f.due)}</p><small>Issued ${escapeHTML(f.issued_at)}<br>${escapeHTML(f.model)}</small></div>`;
}
function renderMVP() {
  $("data-mode").value = state.mode;
  $("as-of").textContent = `${state.mode === "replay" ? "REPLAY" : "Completed daily history"} · ${dateLabel(state.date)}`;
  document.querySelector(".replay-note").textContent = state.mode === "replay" ? "Frozen real prices · offline simulated clock" : "Quotes update independently of daily forecasts";
  $("advance").hidden = state.mode !== "replay";
  $("advance").textContent = state.remaining ? "Next trading day →" : "Sample complete";
  $("reset").textContent = `Reset ${state.mode} experiment`;
  $("history-count").textContent = state.history.length;
  $("provider-status").innerHTML = state.mode === "replay" ? "Historical replay · no network required · 2022 warm-up, 2023–2024 practice" : `Current data · market ${state.market.open ? "open" : "closed"} · ${escapeHTML(state.provider.status)}<br><small>Latest completed exchange session: ${escapeHTML(state.market.latest_completed)}. Next refresh: ${escapeHTML(state.provider.next_attempt)}. ${(state.provider.errors || []).map(escapeHTML).join(" · ")}</small>`;
  $("signals").innerHTML = state.signals.map((s,i)=>`<article class="market-card"><div class="asset-title"><div><h3>${s.name}</h3><span class="ticker">${s.symbol} · ${s.description}</span></div></div><div class="price-row"><span class="price">${money(s.price)}</span><span class="muted">USD</span></div><p class="quote-details">${quoteDetails(s.quote)}</p>${s.chart.length ? chart(s.chart,"sparkline",["#9bbbf4","#b5a0ff","#efc77a"][i],`${s.symbol}: completed daily closes`) : ""}<p class="muted">${s.risk} recent volatility. Trailing 20-session change: ${percent(s.momentum)}. The model combines recent returns and volatility; it can disagree with this trend.</p>${forecastCard(s.forecast,5)}${forecastCard(s.price_forecast,1)}</article>`).join("");
  const p=state.portfolio;
  $("invest").textContent = p ? "Allocation applied" : state.can_invest ? "Apply model allocation ↗" : "Waiting for three usable quotes";
  if(p) {
    $("profile").value=p.profile; $("balance").value=p.initial;
    $("portfolio").innerHTML=`<div class="portfolio-meta">${p.profile} · started with ${money(p.initial)} · ${p.fresh ? "Usable quotes" : "Cached / partial valuation — inspect timestamps"}</div><div class="portfolio-value">${money(p.value)}</div><p class="${p.profit>=0?'gain':'loss'}">${money(p.profit)} (${percent(p.return)}) since ${dateLabel(p.started)}</p>${chart(p.chart.map(x=>x.value),"portfolio-chart","#75ddba","Observed virtual portfolio value")}<div class="holdings">${p.holdings.map(h=>`<div class="holding"><span>${h.name}<small>${h.units.toFixed(6)} units · ${percent(h.weight)}<br>${escapeHTML(h.status)} · ${escapeHTML(h.observed_at)}<br>Entry ${money(h.entry.price)} · ${escapeHTML(h.entry.observed_at)}</small></span><span>${money(h.value)}</span></div>`).join("")}</div>`;
  } else $("portfolio").innerHTML='<div class="empty-state"><h3>Try a fixed allocation.</h3><p>Use a virtual balance from $100 to $1,000,000. Current-data entry needs usable quotes for all three assets. Replay has its own independent portfolio.</p></div>';
  renderAllocation();
  const m=state.performance;
  $("metrics").innerHTML=metric("Five-session accuracy",percent(m.accuracy),`${m.evaluated} evaluated directions`)+metric("Always-Up / momentum",`${percent(m.always_up)} / ${percent(m.momentum)}`,"Same direction observations")+metric("Next-close MAE",money(m.mae),`${m.price_evaluated} evaluated prices · MAPE ${percent(m.mape)}`)+metric("Last-close baseline MAE",money(m.last_close_mae),"Lower MAE is better; the baseline may win")+metric("Selected-direction Brier",m.brier===null?"—":m.brier.toFixed(4),"Lower is better · (probability − correctness)²")+metric("Pending",m.pending,"Outcomes appear only after their target session");
  $("history-rows").innerHTML=state.history.map(h=>`<tr><td>${dateLabel(h.date)}<small>${escapeHTML(h.model)}<br>Issued ${escapeHTML(h.issued_at)}</small></td><td>${h.symbol}</td><td>${h.horizon===5?`${h.direction} · ${percent(h.confidence)}<small>5 sessions</small>`:`${money(h.estimate)}<small>Next close</small>`}</td><td>${dateLabel(h.due)}</td><td>${h.actual_close===null?'Pending':money(h.actual_close)+(h.horizon===5?` · ${h.actual} (${percent(h.return)})`:'')}</td><td class="${h.correct===false?'loss':h.correct===true?'gain':'muted'}">${h.actual_close===null?'Pending':h.horizon===5?(h.correct?'Correct':'Incorrect'):`Error ${money(h.error)} (${percent(h.ape)})`}</td></tr>`).join("");
  renderTraining();
  if(typeof renderJourney === "function") renderJourney();
}
function renderTraining() {
  const t=state.training, a=t.active;
  $("training").innerHTML=`<h3>Automatic daily retraining</h3><p>${a?`Active ${escapeHTML(state.model)}<br>Cutoff ${a.cutoff} · fit ${a.fit_start}–${a.fit_end} (${a.fit_sessions} sessions), last fit label ${a.fit_label_end}; calibration ${a.cal_start}–${a.cal_end} (${a.cal_sessions} sessions).`:'No model yet: waiting for sufficient complete shared daily history.'}</p><p>Latest run: ${escapeHTML(t.runs[0]?.status || "waiting for history")} ${escapeHTML(t.runs[0]?.error || "")}<br>Class counts (fit / calibration): ${a ? escapeHTML(JSON.stringify(a.classes)) + " / " + escapeHTML(JSON.stringify(a.cal_classes)) : "Unavailable"}. Missing Up/Down coverage or a previously unseen calibration class blocks a new version. A fitted Flat class is retained with sigmoid smoothing even if this calibration window has zero Flat examples; its reliability is unproven.</p><p class="muted">Runs while the app is open; startup catches up to the latest available session. Old forecasts and holdings stay fixed.</p><details><summary>Recent training runs (${t.runs.length})</summary>${t.runs.map(r=>`<p>${r.cutoff} · ${escapeHTML(r.status)} · ${escapeHTML(r.finished || r.started)}${r.error?`<br>${escapeHTML(r.error)}`:''}</p>`).join('')}</details><label for="metric-version">Probability reliability / version metrics</label><select id="metric-version"><option value="all">All main forecasts in ${state.mode} mode</option>${Object.keys(state.versions).map(v=>`<option value="${escapeHTML(v)}">${escapeHTML(v)}</option>`).join('')}</select><div id="reliability"></div><h3>Frozen-version comparisons</h3><p class="muted">Consecutive versions make shadow predictions on the same next 20 reference sessions (60 directions and 60 prices each). Both models remain frozen. This is separate from the main daily forecasts; improvement is not guaranteed.</p>${t.comparisons.length?t.comparisons.map(c=>`<details class="comparison" data-status="${c.status}"><summary>${c.start}–${c.end} · ${c.status} · ${c.newer_metrics.evaluated}/60 direction outcomes</summary><p>Older: ${escapeHTML(c.older)}<br>Newer: ${escapeHTML(c.newer)}<br>Final direction outcome due ${c.due}</p><div class="table-scroll"><table><thead><tr><th>Version</th><th>Accuracy</th><th>Price MAE / MAPE</th><th>Brier</th><th>Up / momentum baselines</th><th>Last-close MAE</th><th>Prices</th></tr></thead><tbody>${[['Older',c.older_metrics],['Newer',c.newer_metrics]].map(([n,m])=>`<tr><td>${n}</td><td>${percent(m.accuracy)}</td><td>${money(m.mae)} / ${percent(m.mape)}</td><td>${m.brier===null?"?":m.brier.toFixed(4)}</td><td>${percent(m.always_up)} / ${percent(m.momentum)}</td><td>${money(m.last_close_mae)}</td><td>${m.price_evaluated}/60</td></tr>`).join('')}</tbody></table></div></details>`).join(''):'<p>Pending: a second successful model version is needed.</p>'}`;
  $("metric-version").addEventListener("change",renderReliability); renderReliability();
}
function renderReliability() {
  const m=$("metric-version").value === "all" ? state.performance : state.versions[$("metric-version").value];
  $("reliability").innerHTML=`<p>${m.evaluated} directions · accuracy ${percent(m.accuracy)} · always-Up ${percent(m.always_up)} · momentum ${percent(m.momentum)} · Brier ${m.brier===null?'—':m.brier.toFixed(4)}<br>${m.price_evaluated} prices · MAE ${money(m.mae)} · MAPE ${percent(m.mape)} · last-close MAE ${money(m.last_close_mae)}</p><div class="table-scroll"><table><thead><tr><th>Probability bin</th><th>Count</th><th>Mean prediction</th><th>Observed accuracy</th></tr></thead><tbody>${m.bins.map((b,i)=>`<tr><td>${percent(b.low)}–${percent(b.high)}${i===4?' inclusive':' (upper excluded)'}</td><td>${b.count}</td><td>${percent(b.confidence)}</td><td>${percent(b.accuracy)}</td></tr>`).join('')}</tbody></table></div><p class="muted">Small samples are uncertain. Overlapping five-session targets are not independent. A calibrated estimate is not a guarantee.</p>`;
}
$("data-mode").addEventListener("change",async ()=>{const previous=mode; mode=$("data-mode").value;await request("/api/state");if(state?.mode!==mode){mode=previous;$("data-mode").value=previous;}});
$("refresh").addEventListener("click",()=>request("/api/refresh",{}));
setInterval(()=>{if(!busy && mode==="current" && !document.hidden) request("/api/state");},15000);
